


test:
	mkdir -p marina
	 ../../../../bin/run-marina.R -n ~/Documents/UCSC_VIPER/pathways/brca-tf-regulon.rda \
	-e expression.tab -p phenotypes.tab -t MEK	-r PI3K-MTOR --permutations 100 --output marina
